### ISSUE TITLE
申请加入10进制的收发功能

### ISSUE THREAD

**Issue by zhang-yunqi** [BaudDance/SerialAssistant#12]
在我进行舵机相关的调试时，出现了这样的问题，我希望直接向串口发送10进制的角度数据（这样更便于理解和思考），但是需要从计算器中先换算再发送就很烦人！！！

# 盘点一下可能用到的场合
* 舵机调试
* PID调参
* 模拟电路调参
* 。。。
____
所以加这个还是非常有必要的！！:-)

**Comment by keysking** [comment]
感谢反馈, 我会尽快抽时间考虑添加此功能~
