### ISSUE TITLE
请问up，这个串口助手是怎么实现串口通信的？浏览器不会限制访问么？

### ISSUE THREAD

**Issue by wuxiaobin1995** [BaudDance/SerialAssistant#17]
纯属好奇，因为我之前做上位机开发，都是用electron打包成本地应用再开启串口通信，一直没尝试过网页直接访问串口数据！

**Comment by keysking** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API

**Comment by wuxiaobin1995** [comment]
感谢，已解决！
