### ISSUE TITLE
網頁比例稍大

### ISSUE THREAD

**Issue by wasd52030** [BaudDance/SerialAssistant#7]
如圖，在我的網頁瀏覽器中網頁的比例有點大，導致無法正常使用，需手動縮小比例
![image](https://user-images.githubusercontent.com/71220988/236271111-3b1ca7de-902e-43bc-973a-f84aaf44adf1.png)

**Comment by keysking** [comment]
你好, 方便提供一下电脑显示设置中的分辨率与缩放比例吗

**Comment by wasd52030** [comment]
是這裡的資訊嗎？
![image](https://user-images.githubusercontent.com/71220988/236474583-b8a1bab6-7708-475e-ad31-ba8243b094e0.png)
